project_id = "lnfyoytjfnlwxyxbfhkw"

[functions.create-yoco-checkout]
verify_jwt = false

[functions.yoco-webhook]
verify_jwt = false

[functions.create-lead]
verify_jwt = false

[functions.invite-admin]
verify_jwt = false

[auth]
enabled = true
site_url = "https://sedgepro.co.za/"
additional_redirect_urls = ["https://sedgepro.co.za/*"]
jwt_expiry = 3600
enable_refresh_token_rotation = true

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 8
otp_expiry = 3600

